<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Manual da Atendente - WhatsApp Mobile</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>
body{background:#f4f8fb;color:#101828;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.hero{background:linear-gradient(135deg,#0f172a,#1f6f78,#38a3a5);color:#fff;border-radius:28px}.cardx{background:#fff;border:1px solid rgba(15,23,42,.10);border-radius:22px;box-shadow:0 12px 36px rgba(15,23,42,.08)}.pill{display:inline-flex;align-items:center;gap:7px;border-radius:999px;background:#eef7f8;border:1px solid rgba(31,111,120,.18);padding:6px 11px;font-weight:800;color:#155e66}.why{border-left:4px solid #38a3a5;background:#f8fcfd;border-radius:14px;padding:15px}.topbar{position:sticky;top:0;z-index:20;background:rgba(244,248,251,.9);backdrop-filter:blur(12px);border-bottom:1px solid rgba(15,23,42,.10)}.nav-pills .nav-link{border-radius:999px;font-weight:700;color:#101828}.nav-pills .nav-link.active{background:#1f6f78}.num{display:inline-grid;place-items:center;width:30px;height:30px;border-radius:999px;background:#1f6f78;color:#fff;font-weight:800;margin-right:6px}.term{background:#fff;border:1px solid rgba(15,23,42,.10);border-radius:16px;padding:16px;height:100%}.term strong{color:#155e66}@media print{.topbar,.no-print{display:none!important}body{background:#fff}.cardx,.hero{box-shadow:none}}
</style>
</head>
<body>
<header class="topbar py-2 no-print"><div class="container d-flex justify-content-between align-items-center gap-2"><strong><i class="bi bi-whatsapp text-success"></i> Manual WhatsApp Mobile</strong><div class="d-flex gap-2"><a class="btn btn-sm btn-outline-secondary" href="index.php?page=studio_whatsapp_mobile">Abrir sistema</a><button class="btn btn-sm btn-primary" onclick="window.print()">Imprimir</button></div></div></header>
<main class="container py-4 py-lg-5">
<section class="hero p-4 p-lg-5 mb-4"><span class="badge rounded-pill text-bg-light mb-3">Treinamento da atendente</span><h1 class="display-5 fw-bold">Manual do WhatsApp Mobile</h1><p class="lead col-lg-9 mb-0">Guia para explicar o sistema de atendimento, incluindo a função de cada botão, quando usar e qual cuidado tomar antes de clicar. Porque botão sem explicação vira roleta-russa administrativa.</p></section>
<section class="cardx p-3 mb-4 no-print"><ul class="nav nav-pills gap-2 flex-wrap"><li class="nav-item"><a class="nav-link active" href="#geral">Visão geral</a></li><li class="nav-item"><a class="nav-link" href="#botoes">Botão por botão</a></li><li class="nav-item"><a class="nav-link" href="#fluxo">Fluxo ideal</a></li><li class="nav-item"><a class="nav-link" href="#scripts">Scripts</a></li><li class="nav-item"><a class="nav-link" href="#glossario">Glossário</a></li><li class="nav-item"><a class="nav-link" href="#problemas">Problemas</a></li></ul></section>
<section id="geral" class="cardx p-4 p-lg-5 mb-4"><h2 class="fw-bold mb-3">1. Visão geral</h2><p>O WhatsApp Mobile é a tela usada pela atendente para ver conversas, responder clientes, assumir atendimento, transferir conversas, alternar IA/humano e atualizar cadastro do cliente.</p><div class="why"><strong>Objetivo principal:</strong> responder rápido, não perder histórico, saber quem está cuidando de cada cliente e conduzir a conversa para orçamento, sinal e agendamento.</div></section>
<section id="botoes" class="cardx p-4 p-lg-5 mb-4"><h2 class="fw-bold mb-3">2. Botão por botão</h2><p class="text-secondary">Use esta parte como checklist de treinamento. Leia cada linha e mostre o botão correspondente na tela para ela.</p><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Botão/opção</th><th>O que faz</th><th>Quando usar</th><th>Cuidado</th></tr></thead><tbody>
<tr><td><span class="pill"><i class="bi bi-phone"></i>Abrir sistema</span></td><td>Abre a tela principal do WhatsApp Mobile.</td><td>Início do turno ou retorno ao atendimento.</td><td>Confirmar se está no CRM certo.</td></tr>
<tr><td><span class="pill"><i class="bi bi-search"></i>Buscar</span></td><td>Localiza conversa por nome, telefone ou texto.</td><td>Quando precisa encontrar cliente específico.</td><td>Se não achar, procure por parte do número ou nome.</td></tr>
<tr><td><span class="pill"><i class="bi bi-funnel"></i>Filtros</span></td><td>Mostra grupos como todas, minhas, sem responsável, precisa humano ou IA ativa.</td><td>Para priorizar atendimento.</td><td>Se uma conversa sumir, volte para “Todas”.</td></tr>
<tr><td><span class="pill"><i class="bi bi-arrow-clockwise"></i>Atualizar</span></td><td>Recarrega lista ou conversa.</td><td>Quando mensagens novas não aparecem.</td><td>Não clicar sem parar. Aguarde alguns segundos.</td></tr>
<tr><td><span class="pill"><i class="bi bi-chat-left-text"></i>Abrir conversa</span></td><td>Entra no atendimento do cliente.</td><td>Para ler histórico ou responder.</td><td>Verifique se outro atendente já está cuidando.</td></tr>
<tr><td><span class="pill"><i class="bi bi-person-check"></i>Assumir conversa</span></td><td>Marca a conversa como sua responsabilidade.</td><td>Antes de responder cliente sem responsável.</td><td>Não assumir conversa de outro atendente sem combinar.</td></tr>
<tr><td><span class="pill"><i class="bi bi-person-dash"></i>Liberar conversa</span></td><td>Remove você como responsável.</td><td>Ao terminar, sair do turno ou deixar para outro atender.</td><td>Não liberar conversa pendente sem anotação.</td></tr>
<tr><td><span class="pill"><i class="bi bi-arrow-left-right"></i>Transferir</span></td><td>Passa a conversa para outra pessoa.</td><td>Quando precisa de tatuador, financeiro, agenda ou outro atendente.</td><td>Deixar resumo: o que cliente quer e próximo passo.</td></tr>
<tr><td><span class="pill"><i class="bi bi-robot"></i>Ativar IA</span></td><td>Deixa a conversa em modo automático.</td><td>Triagem simples, fora de horário ou perguntas básicas.</td><td>Não usar em negociação, cliente bravo, saúde, cobertura ou fechamento.</td></tr>
<tr><td><span class="pill"><i class="bi bi-person"></i>Desativar IA / Humano</span></td><td>Tira a IA e deixa atendimento humano.</td><td>Quando precisa de cuidado, venda, decisão ou negociação.</td><td>Depois de desativar, responda. Não deixe o cliente largado.</td></tr>
<tr><td><span class="pill"><i class="bi bi-send"></i>Enviar</span></td><td>Envia a mensagem digitada.</td><td>Depois de escrever a resposta.</td><td>Conferir nome, valor, data e tom da mensagem.</td></tr>
<tr><td><span class="pill"><i class="bi bi-paperclip"></i>Anexar / mídia</span></td><td>Envia ou visualiza imagem, referência ou arquivo.</td><td>Para referências, comprovantes ou orientações.</td><td>Conferir se é o arquivo correto.</td></tr>
<tr><td><span class="pill"><i class="bi bi-mic"></i>Áudio / transcrição</span></td><td>Mostra áudio e, quando houver, texto transcrito.</td><td>Quando cliente manda áudio.</td><td>Se a transcrição parecer estranha, escute o áudio.</td></tr>
<tr><td><span class="pill"><i class="bi bi-person-vcard"></i>Editar cadastro</span></td><td>Abre dados do cliente, lead e informações da conversa.</td><td>Quando descobrir nome, ideia, região, tamanho ou Instagram.</td><td>Não inventar dados. Preencher só o que souber.</td></tr>
<tr><td><span class="pill"><i class="bi bi-save"></i>Salvar cadastro</span></td><td>Grava alterações feitas no perfil.</td><td>Após editar qualquer dado importante.</td><td>Conferir antes de salvar.</td></tr>
<tr><td><span class="pill"><i class="bi bi-link-45deg"></i>Enviar ficha / link</span></td><td>Envia ou copia ficha de cadastro/anamnese, quando disponível.</td><td>Antes do procedimento ou quando faltam dados.</td><td>Explicar que é por segurança e organização.</td></tr>
<tr><td><span class="pill"><i class="bi bi-calendar-check"></i>Agendar</span></td><td>Encaminha para agenda ou reserva de horário, quando disponível.</td><td>Quando cliente fechou valor e sinal.</td><td>Não prometer horário sem conferir agenda.</td></tr>
<tr><td><span class="pill"><i class="bi bi-cash-coin"></i>Sinal / pagamento</span></td><td>Orienta ou registra reserva financeira, quando disponível.</td><td>Quando cliente quer fechar.</td><td>Explicar que o sinal reserva horário e abate do valor final.</td></tr>
<tr><td><span class="pill"><i class="bi bi-arrow-left"></i>Voltar</span></td><td>Retorna para lista ou tela anterior.</td><td>Depois de consultar ou finalizar atendimento.</td><td>Se digitou algo e não enviou, pode perder o texto.</td></tr>
<tr><td><span class="pill"><i class="bi bi-x-circle"></i>Fechar</span></td><td>Fecha painel, modal, filtros ou cadastro.</td><td>Quando terminou de consultar.</td><td>Salvar alterações antes de fechar.</td></tr>
<tr><td><span class="pill"><i class="bi bi-printer"></i>Imprimir</span></td><td>Imprime este manual.</td><td>Para treinamento presencial.</td><td>Conferir se tabelas não foram cortadas.</td></tr>
</tbody></table></div><div class="why mt-4"><strong>Botões mais sensíveis:</strong> Enviar, Transferir, Liberar, Ativar IA, Desativar IA/Humano, Salvar cadastro, Agendar e Sinal. Esses mudam o atendimento de verdade.</div></section>
<section id="fluxo" class="cardx p-4 p-lg-5 mb-4"><h2 class="fw-bold mb-3">3. Fluxo ideal de atendimento</h2><ol><li class="mb-2"><span class="num">1</span>Abrir o WhatsApp Mobile.</li><li class="mb-2"><span class="num">2</span>Ver conversas sem responsável e que precisam de humano.</li><li class="mb-2"><span class="num">3</span>Abrir a conversa e ler histórico.</li><li class="mb-2"><span class="num">4</span>Assumir antes de responder.</li><li class="mb-2"><span class="num">5</span>Pedir ideia, região do corpo, tamanho em cm e referência.</li><li class="mb-2"><span class="num">6</span>Atualizar cadastro/lead.</li><li class="mb-2"><span class="num">7</span>Conduzir para orçamento, sinal e agenda.</li><li class="mb-2"><span class="num">8</span>Liberar ou transferir quando terminar.</li></ol></section>
<section id="scripts" class="cardx p-4 p-lg-5 mb-4"><h2 class="fw-bold mb-3">4. Scripts rápidos</h2><div class="row g-3"><div class="col-lg-6"><div class="border rounded-4 p-3 h-100"><strong>Primeiro contato</strong><p class="mb-0 mt-2">Oi! Me manda a ideia da tattoo, local do corpo, tamanho aproximado em cm e uma referência do estilo?</p></div></div><div class="col-lg-6"><div class="border rounded-4 p-3 h-100"><strong>Sem referência</strong><p class="mb-0 mt-2">Para passar um valor justo preciso de uma referência. Pode ser imagem parecida do Google, Pinterest ou Instagram.</p></div></div><div class="col-lg-6"><div class="border rounded-4 p-3 h-100"><strong>Sinal</strong><p class="mb-0 mt-2">Para reservar o horário trabalhamos com sinal. Ele garante a vaga e é abatido do valor final.</p></div></div><div class="col-lg-6"><div class="border rounded-4 p-3 h-100"><strong>Retomada</strong><p class="mb-0 mt-2">Oi! Passando para ver se ainda quer seguir com sua tattoo. Me confirma a ideia e disponibilidade?</p></div></div></div></section>
<section id="glossario" class="cardx p-4 p-lg-5 mb-4"><h2 class="fw-bold mb-3">5. Glossário rápido</h2><p class="text-secondary">Termos que aparecem no sistema e no atendimento, traduzidos para português de gente normal.</p><div class="row g-3">
<div class="col-md-6 col-lg-4"><div class="term"><strong>Lead</strong><p class="mb-0 mt-2">Pessoa interessada que ainda não virou cliente fechado. É uma oportunidade de venda.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Cliente</strong><p class="mb-0 mt-2">Pessoa que já tem cadastro, histórico mais completo ou já fechou algum atendimento.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Conversa assumida</strong><p class="mb-0 mt-2">Atendimento com responsável definido. Quem assumiu deve acompanhar e responder.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Conversa liberada</strong><p class="mb-0 mt-2">Atendimento sem responsável. Fica disponível para outra pessoa pegar.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Transferir</strong><p class="mb-0 mt-2">Passar a conversa para outra pessoa continuar, geralmente com resumo do caso.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>IA ativa</strong><p class="mb-0 mt-2">A conversa pode ser respondida automaticamente pelo assistente/bot.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Atendimento humano</strong><p class="mb-0 mt-2">A IA fica fora e uma pessoa assume a conversa manualmente.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Precisa humano</strong><p class="mb-0 mt-2">Sinal de que a conversa precisa de uma pessoa, não só resposta automática.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Referência</strong><p class="mb-0 mt-2">Imagem ou exemplo enviado pelo cliente para mostrar estilo, ideia e nível de detalhe.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Orçamento</strong><p class="mb-0 mt-2">Valor estimado ou fechado da tatuagem, baseado em referência, tamanho, local e complexidade.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Sinal</strong><p class="mb-0 mt-2">Valor pago para reservar horário. Normalmente é abatido do valor final.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Agenda</strong><p class="mb-0 mt-2">Organização de data e horário do procedimento. Não prometer sem conferir.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Anamnese</strong><p class="mb-0 mt-2">Perguntas de saúde e segurança antes da tattoo: alergias, medicamentos, cicatrização e afins.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Cobertura</strong><p class="mb-0 mt-2">Tatuagem nova feita por cima de uma antiga. Precisa avaliação com foto boa.</p></div></div>
<div class="col-md-6 col-lg-4"><div class="term"><strong>Observação interna</strong><p class="mb-0 mt-2">Nota para a equipe entender o caso depois. Não é mensagem para o cliente.</p></div></div>
</div><div class="why mt-4"><strong>Dica:</strong> quando houver dúvida entre lead, cliente, orçamento e sinal, pense assim: lead é interesse, orçamento é valor, sinal é compromisso, cliente é relacionamento.</div></section>
<section id="problemas" class="cardx p-4 p-lg-5 mb-4"><h2 class="fw-bold mb-3">6. Problemas comuns</h2><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Situação</th><th>O que fazer</th></tr></thead><tbody><tr><td>Não envia mensagem</td><td>Atualizar página, conferir internet e se a conversa está assumida.</td></tr><tr><td>Cliente mandou áudio longo</td><td>Ler transcrição ou escutar antes de responder.</td></tr><tr><td>Cliente pediu desconto</td><td>Reforçar qualidade, segurança, projeto e formas de pagamento.</td></tr><tr><td>Cobertura</td><td>Pedir foto clara, tamanho e local do corpo. Encaminhar para avaliação.</td></tr><tr><td>Saúde, alergia ou remédio</td><td>Registrar e chamar responsável antes de confirmar procedimento.</td></tr></tbody></table></div></section>
</main><footer class="container pb-5 text-center text-secondary small">Manual v3 - Projeto CRM - WhatsApp Mobile<br><a href="index.php?page=studio_whatsapp_mobile">Abrir WhatsApp Mobile</a></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
